/** The disposable, versioned resident-to-UI status contract. No filesystem or
 * event payload is part of this type; hosts receive only selected facts. */
export interface RuntimeStatusV1 {
  viewModelVersion: "runtime-status-v1";
  observedAt: number;
  actors: {
    phase: string;
    kind: string;
    availability: "available" | "unavailable" | "unknown";
    lastEpisode: string | null;
  }[];
  liveEpisodes: {
    episodeId: string;
    order: string | null;
    actor: string;
    transport: string;
    phase: string;
    startedAt: number;
    elapsedMs: number;
    launchClaims: {
      source: "request" | "none";
      model: string | null;
      effort: string | null;
    };
  }[];
  presence: {
    signal: "away" | "back" | "progress" | "heartbeat" | "unknown";
    present: boolean;
    phase: string | null;
    cadences: { phase: string; nextFireAt: number | null }[];
  };
  holds: {
    kind: "mission" | "handoff" | "dispatch";
    reason: string;
    order: string | null;
  }[];
  budget: {
    status: "configured" | "unavailable";
    episodes: { consumed: number; remaining: number | null };
    wallMs: { consumed: number; remaining: number | null };
    tokens: { consumed: number; remaining: number | null };
  };
  workOrders: {
    status: "available" | "unavailable";
    items: {
      order: string;
      phase: string;
      dependency: "ready" | "blocked" | "unknown";
      verdict: "pass" | "fail" | null;
    }[];
  };
}

/** The generated index is the only work-order status input. Derived and
 * hand-written orders use the same WO-NNN heading and fields. */
export function runtimeOrdersFromIndex(
  text: string | null,
): RuntimeStatusV1["workOrders"] {
  if (text === null) return { status: "unavailable", items: [] };
  if (
    !text.startsWith("# Work orders\n") ||
    !text.includes("This file is generated by")
  )
    throw new Error("invalid generated work-order index");
  const items: RuntimeStatusV1["workOrders"]["items"] = [];
  let section = "";
  let current: Record<string, string> | null = null;
  const flush = () => {
    if (!current) return;
    const order = current["order"]!;
    const phase = current["State"]?.replace(/\.$/u, "");
    if (!phase || !/^[a-z][a-z-]*$/u.test(phase))
      throw new Error(`invalid index status for ${order}`);
    const dependencyText = current["Dependencies"] ?? "";
    const verification = current["Verification"] ?? "";
    const verdict = verification.match(/\((pass|fail)\)/u)?.[1] as
      "pass" | "fail" | undefined;
    items.push({
      order,
      phase,
      dependency: /\bdependency-ready\b/u.test(dependencyText)
        ? "ready"
        : /\bblocked\b/u.test(dependencyText)
          ? "blocked"
          : "unknown",
      verdict: verdict ?? null,
    });
  };
  for (const line of text.split("\n")) {
    const heading = line.match(/^## (Active|Open|Closed|Historical)$/u);
    if (heading) {
      flush();
      current = null;
      section = heading[1]!;
      continue;
    }
    const order = line.match(/^### (WO-\d{3})$/u);
    if (order) {
      flush();
      current =
        section === "Active" || section === "Open"
          ? { order: order[1]! }
          : null;
      continue;
    }
    const field = line.match(/^- ([^:]+): (.*)$/u);
    if (current && field) current[field[1]!] = field[2]!;
  }
  flush();
  if (new Set(items.map((item) => item.order)).size !== items.length)
    throw new Error("duplicate work-order identity in index");
  return { status: "available", items };
}

/** Reject a different version and malformed local files before rendering. */
export function decodeRuntimeStatus(value: unknown): RuntimeStatusV1 {
  const record = (v: unknown): Record<string, unknown> => {
    if (!v || typeof v !== "object" || Array.isArray(v))
      throw new Error("invalid runtime-status-v1 structure");
    return v as Record<string, unknown>;
  };
  const shape = (v: unknown, keys: string[]) => {
    const item = record(v);
    if (Object.keys(item).sort().join(",") !== [...keys].sort().join(","))
      throw new Error("invalid runtime-status-v1 fields");
    return item;
  };
  const str = (v: unknown) => typeof v === "string";
  const nullable = (v: unknown) => v === null || str(v);
  const order = (v: unknown) => typeof v === "string" && /^WO-\d{3}$/u.test(v);
  const number = (v: unknown) =>
    typeof v === "number" && Number.isFinite(v) && v >= 0;
  const list = (v: unknown, check: (item: unknown) => boolean) =>
    Array.isArray(v) && v.every(check);
  const choice = (v: unknown, values: string[]) =>
    str(v) && values.includes(v as string);
  const quantity = (v: unknown) => {
    const item = shape(v, ["consumed", "remaining"]);
    return (
      number(item["consumed"]) &&
      (item["remaining"] === null || number(item["remaining"]))
    );
  };
  const v = shape(value, [
    "viewModelVersion",
    "observedAt",
    "actors",
    "liveEpisodes",
    "presence",
    "holds",
    "budget",
    "workOrders",
  ]);
  const presence = shape(v["presence"], [
    "signal",
    "present",
    "phase",
    "cadences",
  ]);
  const budget = shape(v["budget"], ["status", "episodes", "wallMs", "tokens"]);
  const orders = shape(v["workOrders"], ["status", "items"]);
  if (
    v["viewModelVersion"] !== "runtime-status-v1" ||
    !number(v["observedAt"]) ||
    !list(v["actors"], (entry) => {
      const row = shape(entry, [
        "phase",
        "kind",
        "availability",
        "lastEpisode",
      ]);
      return (
        str(row["phase"]) &&
        str(row["kind"]) &&
        choice(row["availability"], ["available", "unavailable", "unknown"]) &&
        nullable(row["lastEpisode"])
      );
    }) ||
    !list(v["liveEpisodes"], (entry) => {
      const row = shape(entry, [
        "episodeId",
        "order",
        "actor",
        "transport",
        "phase",
        "startedAt",
        "elapsedMs",
        "launchClaims",
      ]);
      const claim = shape(row["launchClaims"], ["source", "model", "effort"]);
      return (
        str(row["episodeId"]) &&
        (row["order"] === null || order(row["order"])) &&
        str(row["actor"]) &&
        str(row["transport"]) &&
        str(row["phase"]) &&
        number(row["startedAt"]) &&
        number(row["elapsedMs"]) &&
        choice(claim["source"], ["request", "none"]) &&
        nullable(claim["model"]) &&
        nullable(claim["effort"])
      );
    }) ||
    !choice(presence["signal"], [
      "away",
      "back",
      "progress",
      "heartbeat",
      "unknown",
    ]) ||
    typeof presence["present"] !== "boolean" ||
    !nullable(presence["phase"]) ||
    !list(presence["cadences"], (entry) => {
      const row = shape(entry, ["phase", "nextFireAt"]);
      return (
        str(row["phase"]) &&
        (row["nextFireAt"] === null || number(row["nextFireAt"]))
      );
    }) ||
    !list(v["holds"], (entry) => {
      const row = shape(entry, ["kind", "reason", "order"]);
      return (
        choice(row["kind"], ["mission", "handoff", "dispatch"]) &&
        str(row["reason"]) &&
        (row["order"] === null || order(row["order"]))
      );
    }) ||
    !choice(budget["status"], ["configured", "unavailable"]) ||
    !quantity(budget["episodes"]) ||
    !quantity(budget["wallMs"]) ||
    !quantity(budget["tokens"]) ||
    !choice(orders["status"], ["available", "unavailable"]) ||
    !list(orders["items"], (entry) => {
      const row = shape(entry, ["order", "phase", "dependency", "verdict"]);
      return (
        order(row["order"]) &&
        str(row["phase"]) &&
        choice(row["dependency"], ["ready", "blocked", "unknown"]) &&
        (row["verdict"] === null || choice(row["verdict"], ["pass", "fail"]))
      );
    })
  )
    throw new Error("invalid runtime-status-v1 values");
  return value as RuntimeStatusV1;
}
