import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { syncBuiltinESMExports } from "node:module";
import { spawnSync } from "node:child_process";
import { decodeLog } from "@dotln/kernel";
import { createHash } from "node:crypto";
import {
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import {
  actorCatalog,
  type ActorResult,
  type ActorSpec,
} from "../src/actor-catalog.js";
import { ResidentHost } from "../src/resident-host.js";
import {
  ResidentStore,
  recordPresenceObservation,
  replayResident,
} from "../src/resident-store.js";
import {
  decodeResidentConfiguration,
  type ResidentState,
} from "../src/resident-state.js";
import { projectRuntimeStatus } from "../src/runtime-status.js";

const index = `# Work orders

This file is generated by \`npm run work-orders -- index\`.

## Active

### WO-114

- State: active.
- Dependencies: typed; dependency-ready.
- Verification: none recorded.

## Open

### WO-158

- State: queued.
- Dependencies: typed; blocked by WO-114.
- Verification: VER-001 (fail).

## Closed

### WO-120

- State: closed.
`;
const fixture = JSON.parse(
  readFileSync(
    new URL("../../fixtures/wo067-presence.json", import.meta.url),
    "utf8",
  ),
);
const hash = (value: string) =>
  createHash("sha256").update(value).digest("hex");
const result: ActorResult = {
  exitCode: 0,
  signal: null,
  stdoutSha256: hash("ok\n"),
  firstLine: "ok",
  verified: true,
  reason: "completed",
};
const read = (directory: string) =>
  readFileSync(join(directory, "runtime-status-v1.json"), "utf8");

test("WO-114 per-event status, tick, privacy and restart transcript", async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-status-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const indexPath = join(directory, "index.md");
  writeFileSync(indexPath, index);
  const spec: ActorSpec = {
    kind: "script",
    effect: "repo.inspect",
    surface: "fixture.source",
    resources: { files: 1, lines: 0, tokens: 0 },
    command: [process.execPath, "-e", "process.stdout.write('ok\\n')"],
    cwd: directory,
    timeoutMs: 1000,
    expectedStdoutSha256: hash("ok\n"),
  };
  const configuration = decodeResidentConfiguration({
    ...structuredClone(fixture),
    policyId: "fixture.progressive",
    actors: Object.fromEntries(
      ["probe", "widen", "peak"].map((phase) => [phase, spec]),
    ),
    evidence: ["verified-input"],
  });
  let at = 0;
  let finish!: (result: ActorResult) => void;
  const options = {
    directory,
    policyId: "fixture.progressive",
    configuration,
    workOrderIndexPath: indexPath,
    now: () => at,
    capabilities: () => ["adapter.fixture"],
    catalog: {
      ...actorCatalog,
      script: {
        kind: "script" as const,
        available: () => null,
        run: () => ({
          completed: new Promise<ActorResult>((resolve) => {
            finish = resolve;
          }),
          kill: () => {},
        }),
      },
    },
  };
  const host = new ResidentHost(options);
  await host.start();
  const transcript: string[] = [hash(read(directory))];
  const store = new ResidentStore(directory, {}, indexPath);
  await store.transaction((tx) =>
    tx.append("OperatorPresenceChanged", { presence: "away" }, 0),
  );
  transcript.push(hash(read(directory)));
  at = 10;
  const tick = host.tick();
  for (let i = 0; i < 200; i++) {
    if (JSON.parse(read(directory)).liveEpisodes.length === 1) break;
    await delay(10);
  }
  const live = JSON.parse(read(directory));
  assert.equal(live.liveEpisodes.length, 1);
  assert.equal(live.liveEpisodes[0].startedAt, 10);
  assert.equal(live.liveEpisodes[0].elapsedMs, 0);
  assert.deepEqual(live.workOrders.items, [
    { order: "WO-114", phase: "active", dependency: "ready", verdict: null },
    {
      order: "WO-158",
      phase: "queued",
      dependency: "blocked",
      verdict: "fail",
    },
  ]);
  transcript.push(hash(read(directory)));
  at = 30;
  await store.transaction((tx) => tx.sample(at));
  assert.equal(JSON.parse(read(directory)).liveEpisodes[0].elapsedMs, 20);
  transcript.push(hash(read(directory)));
  finish(result);
  await tick;
  const final = read(directory);
  assert.deepEqual(JSON.parse(final).liveEpisodes, []);
  transcript.push(hash(final));
  assert.ok(!final.includes(directory), "physical store path stays private");
  assert.ok(!/sessionId|hostName|hostname|endpoint|cwd|command/u.test(final));
  const log = store.read();
  host.close();
  unlinkSync(join(directory, "runtime-status-v1.json"));
  const restarted = new ResidentHost(options);
  await restarted.start();
  assert.equal(read(directory), final);
  assert.equal(restarted.store.read(), log);
  restarted.close();
  assert.deepEqual(transcript, [
    "c108fac47e4d7710367d4f0dc35a32387e76f0d865c14a1e3d1a8cba009322c7",
    "4e91c9751c23a6afbd710c50caf316ae31a0c6f8334068df63bcf827666d3160",
    "256d1944c49e087e5a6af826c06b9b81e5ce8fc58365b0834bb176cc63c75813",
    "531d99893c75e1035544dfe9a7eec5b3e450a21a88db51691de4190e0bee5f6d",
    "1c0c459609e660129b0ab65795c34e6d90541a1522f22e0d83b2d58568f812b2",
  ]);
});

function configuration(directory: string) {
  const spec: ActorSpec = {
    kind: "script",
    effect: "repo.inspect",
    surface: "fixture.source",
    resources: { files: 1, lines: 0, tokens: 0 },
    command: [process.execPath, "-e", "process.stdout.write('ok\\n')"],
    cwd: directory,
    timeoutMs: 1000,
    expectedStdoutSha256: hash("ok\n"),
  };
  return decodeResidentConfiguration({
    ...structuredClone(fixture),
    policyId: "fixture.progressive",
    actors: Object.fromEntries(
      ["probe", "widen", "peak"].map((phase) => [phase, spec]),
    ),
    evidence: ["verified-input"],
  });
}

test("WO-114 helper and installed-snapshot heartbeat share the host's index and replay every publication", async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-status-writers-"));
  const indexPath = join(directory, "index.md");
  writeFileSync(
    indexPath,
    index.replace(
      "### WO-158",
      "### WO-999\n\n- Provenance: derived from fixture intent.",
    ),
  );
  const selectedIndex = readFileSync(indexPath, "utf8");
  const snapshots: { bytes: string; log: string }[] = [];
  const rename = fs.renameSync;
  t.mock.method(fs, "renameSync", (from: fs.PathLike, to: fs.PathLike) => {
    rename(from, to);
    if (String(to) === join(directory, "runtime-status-v1.json"))
      snapshots.push({
        bytes: read(directory),
        log: readFileSync(join(directory, "events.jsonl"), "utf8"),
      });
  });
  syncBuiltinESMExports();
  t.after(() => {
    t.mock.restoreAll();
    syncBuiltinESMExports();
  });
  const host = new ResidentHost({
    directory,
    configuration: configuration(directory),
    policyId: "fixture.progressive",
    workOrderIndexPath: indexPath,
    now: () => 0,
  });
  t.after(() => host.close());
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  await host.start();
  await recordPresenceObservation(
    directory,
    { kind: "away" },
    undefined,
    () => 1,
  );
  const root = new URL("../../../../", import.meta.url);
  const hook = readFileSync(
    new URL(".claude/hooks/presence-pretooluse.mjs", root),
    "utf8",
  );
  const snapshot = hook.match(/\.runtime\/harness\/[a-z0-9]+/u)![0];
  const { recordHarnessHeartbeat } = await import(
    new URL(
      `${snapshot}/packages/skeleton/dist/src/presence-heartbeat.js`,
      root,
    ).href
  );
  await recordHarnessHeartbeat(
    "PreToolUse",
    {
      hook_event_name: "PreToolUse",
      session_id: "00000000-0000-0000-0000-000000000000",
    },
    { DOTLN_RESIDENT_STORE: directory },
    () => 2,
  );
  await new ResidentStore(directory).transaction((tx) => tx.sample(3));
  for (const snapshot of snapshots) {
    const events = decodeLog(snapshot.log);
    const state = replayResident(snapshot.log).state.resident as unknown as
      ResidentState | undefined;
    assert.equal(
      snapshot.bytes,
      JSON.stringify(
        projectRuntimeStatus(state, events, selectedIndex),
        null,
        2,
      ) + "\n",
    );
    const view = JSON.parse(snapshot.bytes);
    assert.deepEqual(
      view.workOrders.items.map((row: { order: string }) => row.order),
      ["WO-114", "WO-999"],
    );
    assert.ok(!snapshot.bytes.includes(directory));
    assert.ok(!snapshot.bytes.includes("00000000-0000-0000-0000-000000000000"));
  }
  // Start publishes twice; each helper appends observation + clock; final sample.
  assert.equal(snapshots.length, 7);
  const latest = read(directory);
  unlinkSync(join(directory, "runtime-status-v1.json"));
  await new ResidentStore(directory).transaction(() => {});
  assert.equal(read(directory), latest);
});

test("WO-114 CLI binds the selected launchpad's configured index root", (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-status-launchpad-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const orders = join(directory, "orders");
  mkdirSync(orders);
  writeFileSync(
    join(directory, "dotln.config.json"),
    JSON.stringify({ version: 1, roots: { workOrders: "orders" } }),
  );
  writeFileSync(
    join(orders, "README.md"),
    index.replaceAll("WO-158", "WO-999"),
  );
  const store = join(directory, "resident");
  mkdirSync(store);
  writeFileSync(
    join(store, "resident.json"),
    JSON.stringify(configuration(store)),
  );
  const cli = spawnSync(
    process.execPath,
    [
      new URL("../src/dotln.js", import.meta.url).pathname,
      "resident",
      "--store",
      store,
      "--policy",
      "fixture.progressive",
      "--once",
    ],
    { env: { ...process.env, DOTLN_LAUNCHPAD: directory }, encoding: "utf8" },
  );
  assert.equal(cli.status, 0, cli.stderr);
  assert.deepEqual(
    JSON.parse(read(store)).workOrders.items.map(
      (row: { order: string }) => row.order,
    ),
    ["WO-114", "WO-999"],
  );
});

test("WO-114 failed publication cannot abort start, presence or dispatch and the next tick rebuilds", async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-status-failure-"));
  const indexPath = join(directory, "index.md");
  writeFileSync(indexPath, index);
  const target = join(directory, "runtime-status-v1.json");
  mkdirSync(target);
  let runs = 0;
  let at = 0;
  const host = new ResidentHost({
    directory,
    policyId: "fixture.progressive",
    configuration: configuration(directory),
    workOrderIndexPath: indexPath,
    now: () => at,
    capabilities: () => ["adapter.fixture"],
    catalog: {
      ...actorCatalog,
      script: {
        kind: "script",
        available: () => null,
        run: () => {
          runs++;
          return { completed: Promise.resolve(result), kill: () => {} };
        },
      },
    },
  });
  t.after(() => host.close());
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  await host.start();
  await recordPresenceObservation(
    directory,
    { kind: "away" },
    undefined,
    () => 0,
  );
  const events = () => decodeLog(host.store.read());
  assert.deepEqual(
    events()
      .slice(-2)
      .map((event) => event.type),
    ["OperatorPresenceObserved", "ClockSampled"],
  );
  at = 10;
  await host.tick();
  assert.equal(runs, 1);
  assert.ok(events().some((event) => event.type === "ScriptEpisodeObserved"));
  assert.ok(!events().some((event) => event.type === "ScriptEpisodeLost"));
  rmSync(target, { recursive: true });
  // An unreadable index only makes the order section unavailable.
  unlinkSync(indexPath);
  mkdirSync(indexPath);
  await host.tick();
  assert.equal(JSON.parse(read(directory)).workOrders.status, "unavailable");
  rmSync(indexPath, { recursive: true });
  writeFileSync(indexPath, index);
  await host.tick();
  assert.equal(JSON.parse(read(directory)).workOrders.status, "available");
  assert.ok(!readdirSync(directory).some((name) => name.endsWith(".tmp")));
  const latest = read(directory);
  host.close();
  const restarted = new ResidentHost({
    directory,
    configuration: configuration(directory),
    policyId: "fixture.progressive",
  });
  await restarted.start();
  assert.equal(read(directory), latest);
  restarted.close();
});
