import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { arch, platform, release } from "node:os";
import {
  HAND_COMPUTED_COMMAND_VECTOR,
  buildIdCorpus,
  referenceCommandId,
  referenceStableHash,
} from "./id-corpus-lib.mjs";
import { TOOLCHAIN_PROFILE } from "./manifest-lib.mjs";
import { enumeratePrograms } from "./program-corpus-lib.mjs";
import {
  PATHS,
  PINNED_BASE_COMMIT,
  RECORDED_SEED,
  REPO_ROOT,
  fixtureDescriptor,
  parseGeneratorArgs,
  sha256,
} from "./wo101-support.mjs";

const manifestBytes = readFileSync(PATHS.manifest, "utf8");
const manifest = JSON.parse(manifestBytes);

test("WO-101 generators are seed-deterministic and the seed materially affects generated bytes", () => {
  const first = buildIdCorpus(RECORDED_SEED);
  const second = buildIdCorpus(RECORDED_SEED);
  assert.deepEqual(
    first.files.map((file) => file.bytes),
    second.files.map((file) => file.bytes),
  );
  const different = buildIdCorpus(`${RECORDED_SEED}-different`);
  assert.notEqual(
    sha256(first.files[0].bytes),
    sha256(different.files[0].bytes),
  );
  assert.notEqual(
    sha256(first.files[1].bytes),
    sha256(different.files[1].bytes),
  );

  const programOrder = enumeratePrograms(RECORDED_SEED).map((program) =>
    JSON.stringify(program),
  );
  const repeatedOrder = enumeratePrograms(RECORDED_SEED).map((program) =>
    JSON.stringify(program),
  );
  const differentOrder = enumeratePrograms(`${RECORDED_SEED}-different`).map(
    (program) => JSON.stringify(program),
  );
  assert.deepEqual(repeatedOrder, programOrder);
  assert.notDeepEqual(differentOrder.slice(0, 50), programOrder.slice(0, 50));
  assert.deepEqual(
    new Set(differentOrder),
    new Set(programOrder),
    "seed must reorder, never change, the exhaustive Program set",
  );
});

test("WO-101 generator CLI parser rejects ambiguous, missing, and stray inputs", () => {
  assert.deepEqual(parseGeneratorArgs(["--seed", RECORDED_SEED, "--check"]), {
    mode: "check",
    seed: RECORDED_SEED,
  });
  assert.deepEqual(parseGeneratorArgs(["--write", "--seed", RECORDED_SEED]), {
    mode: "write",
    seed: RECORDED_SEED,
  });
  assert.throws(() => parseGeneratorArgs([]), /choose exactly one/);
  assert.throws(() => parseGeneratorArgs(["--check"]), /--seed is required/);
  assert.throws(
    () => parseGeneratorArgs(["--check", "--write", "--seed", RECORDED_SEED]),
    /choose exactly one/,
  );
  assert.throws(
    () =>
      parseGeneratorArgs([
        "--check",
        "--seed",
        RECORDED_SEED,
        "--seed",
        RECORDED_SEED,
      ]),
    /only once/,
  );
  assert.throws(
    () => parseGeneratorArgs(["--check", "--seed", RECORDED_SEED, "--wat"]),
    /unknown argument/,
  );
});

test("WO-101 hash generator source contains no integer-wide alternate path and planted command anchor is literal", () => {
  const source = readFileSync(
    `${REPO_ROOT}/corpus/harness/id-corpus-lib.mjs`,
    "utf8",
  );
  const imports = [...source.matchAll(/\bfrom\s+"([^"]+)";/g)].map(
    (match) => match[1],
  );
  assert.deepEqual(
    imports,
    ["./wo101-support.mjs"],
    "reference oracle must import only shared non-kernel helpers",
  );
  assert.doesNotMatch(
    source,
    /(?:packages\/kernel|@dotln\/kernel|\/dist\/src\/index\.js)/,
  );
  assert.doesNotMatch(source, /BigInt\s*\(/);
  assert.doesNotMatch(source, /\b(?:[0-9][0-9_]*|0[xob][0-9a-f_]+)n\b/i);
  assert.equal(
    referenceCommandId("a", undefined, 0, 0),
    HAND_COMPUTED_COMMAND_VECTOR.expected,
  );
  assert.equal(HAND_COMPUTED_COMMAND_VECTOR.preimage, "ws:a:0:0");
  assert.match(
    HAND_COMPUTED_COMMAND_VECTOR.derivation,
    /per-byte unsigned high:low recurrence/,
  );
  let prefix = "";
  for (const step of HAND_COMPUTED_COMMAND_VECTOR.byteTrace) {
    prefix += Buffer.from(step.byteHex, "hex").toString("utf8");
    assert.equal(referenceStableHash(prefix), step.state);
  }
  assert.equal(
    `cmd_${HAND_COMPUTED_COMMAND_VECTOR.byteTrace.at(-1).state}`,
    HAND_COMPUTED_COMMAND_VECTOR.expected,
  );
  assert.equal(referenceCommandId("ws", "ep", 3, 0), "cmd_c835adb882f3d562");
  assert.equal(
    referenceCommandId("ws", undefined, 3, 0),
    "cmd_030cb49f8b1f142c",
  );
  assert.equal(referenceCommandId("ws", "", 3, 0), "cmd_030cb49f8b1f142c");
  assert.equal(
    referenceCommandId("ws", undefined, 5, 2),
    "cmd_1510809f958568d0",
  );
});

test("WO-101 manifest hashes every committed fixture and admits no unmanifested fixture", () => {
  const described = new Set();
  let totalRows = 0;
  let totalBytes = 0;
  for (const fixture of manifest.fixtures) {
    const bytes = readFileSync(`${REPO_ROOT}/${fixture.path}`, "utf8");
    const rows = bytes === "" ? 0 : bytes.trimEnd().split("\n").length;
    assert.deepEqual(fixtureDescriptor(fixture.path, bytes, rows), fixture);
    described.add(fixture.path);
    totalRows += rows;
    totalBytes += Buffer.byteLength(bytes);
  }
  assert.deepEqual(manifest.fixtureTotals, {
    files: described.size,
    rows: totalRows,
    bytes: totalBytes,
  });

  const actual = [
    ...readdirSync(PATHS.programFixtures)
      .filter((name) => name.endsWith(".jsonl"))
      .map((name) => `corpus/fixtures/program/${name}`),
    ...readdirSync(PATHS.idFixtures)
      .filter((name) => name.endsWith(".jsonl"))
      .map((name) => `corpus/fixtures/ids/${name}`),
  ];
  assert.deepEqual(new Set(actual), described);
});

test("WO-101 manifest pins the base, seeds, toolchain, budgets, and run-log interpretation", () => {
  assert.equal(manifest.workOrderId, "WO-101");
  assert.equal(manifest.pinnedBaseCommit, PINNED_BASE_COMMIT);
  assert.deepEqual(manifest.seeds, {
    program: RECORDED_SEED,
    ids: RECORDED_SEED,
  });
  assert.deepEqual(
    manifest.ids.handComputedCommandAnchor,
    HAND_COMPUTED_COMMAND_VECTOR,
  );
  assert.deepEqual(manifest.toolchainProfile, TOOLCHAIN_PROFILE);
  assert.equal(TOOLCHAIN_PROFILE.node, process.version);
  assert.equal(
    TOOLCHAIN_PROFILE.npm,
    execFileSync("npm", ["--version"], { encoding: "utf8" }).trim(),
  );
  assert.equal(
    TOOLCHAIN_PROFILE.typescript,
    execFileSync(`${REPO_ROOT}/node_modules/.bin/tsc`, ["--version"], {
      encoding: "utf8",
    })
      .trim()
      .replace(/^Version /, ""),
  );
  assert.equal(TOOLCHAIN_PROFILE.platform, platform());
  assert.equal(TOOLCHAIN_PROFILE.architecture, arch());
  assert.equal(TOOLCHAIN_PROFILE.osKernel, `Darwin ${release()}`);
  assert.match(manifest.evidence.runLog, new RegExp(PINNED_BASE_COMMIT));
  assert.match(manifest.evidence.runLogCommitMeaning, /pinned base commit/);
  assert.match(
    manifest.layoutExtension.architectureSyncRequired,
    /later authorized documentation pass/,
  );

  const programFixtures = manifest.fixtures.filter((fixture) =>
    fixture.path.startsWith("corpus/fixtures/program/"),
  );
  const idFixtures = manifest.fixtures.filter((fixture) =>
    fixture.path.startsWith("corpus/fixtures/ids/"),
  );
  assert.ok(
    programFixtures.length <= manifest.program.committedBudget.maximumFiles,
  );
  assert.ok(
    programFixtures.reduce((sum, fixture) => sum + fixture.bytes, 0) <=
      manifest.program.committedBudget.maximumTotalBytes,
  );
  assert.ok(idFixtures.length <= manifest.ids.committedBudget.maximumFiles);
  assert.ok(
    idFixtures.reduce((sum, fixture) => sum + fixture.bytes, 0) <=
      manifest.ids.committedBudget.maximumTotalBytes,
  );
});
