import { docRelative } from "./config.mjs";
// Source files imported by the evidence tools plus their fixed data/build inputs.
// Generated harness output and selected edition output are deliberately absent.
// Package indexes load their complete export graphs; these are explicit files.
const commonSources = [
  "package-lock.json",
  "package.json",
  "packages/compiler/package.json",
  "packages/compiler/src/artifact-identity.ts",
  "packages/compiler/src/attribution.mjs",
  "packages/compiler/src/authority.ts",
  "packages/compiler/src/compile.ts",
  "packages/compiler/src/feedback.ts",
  "packages/compiler/src/harness.ts",
  "packages/compiler/src/codex-continuation.mjs",
  "packages/compiler/src/index.ts",
  "packages/compiler/src/normalize.ts",
  "packages/compiler/src/operator-control.mjs",
  "packages/compiler/src/presence-schema.ts",
  "packages/compiler/src/presence.ts",
  "packages/compiler/src/render.ts",
  "packages/compiler/src/seiri.ts",
  "packages/compiler/src/senses.ts",
  "packages/compiler/src/types.ts",
  "packages/compiler/src/verification.ts",
  "packages/compiler/src/views.ts",
  "packages/compiler/tsconfig.json",
  "packages/kernel/package.json",
  "packages/kernel/src/continuation.ts",
  "packages/kernel/tsconfig.json",
  "packages/skeleton/package.json",
  "packages/skeleton/src/evidence-editions.mjs",
  "packages/skeleton/src/version.ts",
  "packages/skeleton/src/execution-environment.ts",
  "packages/skeleton/src/source-change-environment.ts",
  "packages/skeleton/src/source-change-command.ts",
  "packages/skeleton/src/source-change-host.ts",
  "packages/skeleton/src/source-change-state.ts",
  "packages/skeleton/src/source-change-worktree.ts",
  "packages/skeleton/src/reactor.ts",
  "packages/skeleton/src/repair.ts",
  "packages/skeleton/src/repair-host.ts",
  "packages/skeleton/src/resident-state.ts",
  "packages/skeleton/src/presence-signals.ts",
  "packages/skeleton/src/presence-heartbeat.ts",
  "packages/skeleton/src/resident-store.ts",
  "packages/skeleton/src/worker-store.ts",
  "packages/skeleton/src/verification-protocol.ts",
  "packages/skeleton/src/plan-refutation-protocol.ts",
  "packages/skeleton/src/worker-protocol.ts",
  "packages/skeleton/src/presence-machine.ts",
  "packages/skeleton/src/actor-catalog.ts",
  "packages/skeleton/src/actor-contract.ts",
  "packages/skeleton/src/cli-actor-contract.ts",
  "packages/skeleton/src/cli-actor.ts",
  "packages/skeleton/src/cli-episode.ts",
  "packages/skeleton/src/handoff-contract.ts",
  "packages/skeleton/src/handoff-actor.ts",
  "packages/skeleton/src/work-candidate.ts",
  "packages/skeleton/src/script-episode.ts",
  "packages/skeleton/src/discovery-sandbox.ts",
  "packages/skeleton/src/discovery-actor.ts",
  "packages/skeleton/src/discovery-cli.ts",
  "packages/skeleton/src/discovery.ts",
  "packages/skeleton/tsconfig.json",
  "scripts/build.mjs",
  "scripts/lib/evidence-sources.mjs",
  "tsconfig.json",
];

const authoritySources = (root) => [
  ...commonSources,
  docRelative(root, "evidence", "WO-042/artifact-identity/audit.json"),
  docRelative(
    root,
    "evidence",
    "WO-042/artifact-identity/negative-transcripts.json",
  ),
  docRelative(root, "evidence", "WO-042/artifact-identity/scenario.jsonl"),
  docRelative(
    root,
    "evidence",
    "WO-042/artifact-identity/semantic-hash-inventory.json",
  ),
  docRelative(root, "evidence", "WO-042/authority-baseline.json"),
  docRelative(root, "evidence", "WO-042/authority.json"),
  docRelative(root, "evidence", "WO-042/bundle-diff.json"),
  docRelative(root, "evidence", "WO-042/verification/events.jsonl"),
  docRelative(root, "evidence", "WO-042/verification/matrix.json"),
  docRelative(root, "evidence", "WO-042/verification/stale-status.json"),
  docRelative(root, "evidence", "WO-042/verification/stale-status.txt"),
  "packages/compiler/fixtures/wo029-entropy-reducer.json",
  "packages/compiler/fixtures/wo029-identities.json",
  "packages/compiler/test/authority-fixture.ts",
  "packages/kernel/src/core.ts",
  "packages/kernel/src/index.ts",
  "packages/kernel/src/store.ts",
  "packages/kernel/src/types.ts",
  "packages/skeleton/fixtures/wo003-decision-traces.json",
  "packages/skeleton/src/feedback-boundary.ts",
  "packages/skeleton/src/feedback-source-comments.ts",
  "packages/skeleton/src/gate-deadlines.mjs",
  "packages/skeleton/src/gate-evidence.mjs",
  "packages/skeleton/src/harness-command.ts",
  "packages/skeleton/src/harness-host.ts",
  "packages/skeleton/src/subagent-budget.ts",
  "packages/skeleton/src/observed-facts.ts",
  "packages/skeleton/src/correction-observation.mjs",
  "packages/skeleton/src/loadouts/contributor.ts",
  "packages/skeleton/src/loadouts/entropy-reducer.ts",
  "packages/skeleton/src/loadouts/executor-supports.ts",
  "packages/skeleton/src/loadouts/feedback.ts",
  "packages/skeleton/src/loadouts/goal-alignment.ts",
  "packages/skeleton/src/loadouts/plan-refuter.ts",
  "packages/skeleton/src/loadouts/process-cost.ts",
  "packages/skeleton/src/loadouts/prompt-support.ts",
  "packages/skeleton/src/plan-refutation-protocol.ts",
  "packages/skeleton/src/usage-observation.mjs",
  "packages/skeleton/src/worker-protocol.ts",
  "packages/skeleton/src/writer-teardown.mjs",
  "scripts/authority-evidence.mjs",
  "scripts/lib/harness.mjs",
  "scripts/lib/paths.mjs",
  "scripts/lib/terms.mjs",
];

const artifactIdentitySources = (root) => [
  ...commonSources,
  "packages/compiler/fixtures/wo029-entropy-reducer.json",
  "packages/compiler/fixtures/wo029-identities.json",
  "corpus/harness/id-corpus-lib.mjs",
  "corpus/harness/wo101-support.mjs",
  docRelative(root, "evidence", "WO-029/baseline.json"),
  "packages/kernel/src/core.ts",
  "packages/kernel/src/index.ts",
  "packages/kernel/src/store.ts",
  "packages/kernel/src/types.ts",
  "packages/skeleton/fixtures/repo-tree.json",
  "packages/skeleton/fixtures/wo003-decision-traces.json",
  "packages/skeleton/fixtures/wo029-legacy-scenario.jsonl",
  "packages/skeleton/src/artifact-audit.ts",
  "packages/skeleton/src/artifact-identity.ts",
  "packages/skeleton/src/audit.ts",
  "packages/skeleton/src/beacon-codebook.mjs",
  "packages/skeleton/src/beacon-perception.ts",
  "packages/skeleton/src/beacon-v3-codebook.mjs",
  "packages/skeleton/src/control-beacon.ts",
  "packages/skeleton/src/control-codebook.mjs",
  "packages/skeleton/src/loadouts/entropy-reducer.ts",
  "packages/skeleton/src/plan-refutation-protocol.ts",
  "packages/skeleton/src/scenario.ts",
  "packages/skeleton/src/live-reactor-driver.ts",
  "packages/skeleton/src/verification-protocol.ts",
  "packages/skeleton/src/worker-protocol.ts",
  "scripts/artifact-identity-evidence.mjs",
];

const verificationSources = (root) => [
  ...commonSources,
  "packages/kernel/src/core.ts",
  "packages/kernel/src/index.ts",
  "packages/kernel/src/store.ts",
  "packages/kernel/src/types.ts",
  "packages/skeleton/src/artifact-identity.ts",
  "packages/skeleton/src/beacon-codebook.mjs",
  "packages/skeleton/src/beacon-perception.ts",
  "packages/skeleton/src/beacon-v3-codebook.mjs",
  "packages/skeleton/src/control-codebook.mjs",
  "packages/skeleton/src/gate-deadlines.mjs",
  "packages/skeleton/src/plan-refutation-protocol.ts",
  "packages/skeleton/src/verification-demo.ts",
  "packages/skeleton/src/verification-fake.ts",
  "packages/skeleton/src/verification-host.ts",
  "packages/skeleton/src/verification-worktree.ts",
  "packages/skeleton/src/verification-protocol.ts",
  "packages/skeleton/src/verification.ts",
  "packages/skeleton/src/worker-protocol.ts",
  "packages/skeleton/src/worker-status.ts",
  "packages/skeleton/src/worker-store.ts",
  "packages/skeleton/src/worker-worktree.ts",
  "scripts/verification-evidence.mjs",
];

const feedbackSources = (root) => [
  ...commonSources,
  docRelative(root, "discovery", "environment.json"),
  "packages/kernel/src/core.ts",
  "packages/kernel/src/index.ts",
  "packages/kernel/src/store.ts",
  "packages/kernel/src/types.ts",
  "packages/skeleton/src/artifact-identity.ts",
  "packages/skeleton/src/beacon-codebook.mjs",
  "packages/skeleton/src/beacon-perception.ts",
  "packages/skeleton/src/beacon-v3-codebook.mjs",
  "packages/skeleton/src/control-codebook.mjs",
  "packages/skeleton/src/feedback-audit.ts",
  "packages/skeleton/src/feedback-boundary.ts",
  "packages/skeleton/src/feedback-selfhost.ts",
  "packages/skeleton/src/feedback-source-comments.ts",
  "packages/skeleton/src/gate-deadlines.mjs",
  "packages/skeleton/src/gate-evidence.mjs",
  "packages/skeleton/src/harness-command.ts",
  "packages/skeleton/src/harness-host.ts",
  "packages/skeleton/src/subagent-budget.ts",
  "packages/skeleton/src/observed-facts.ts",
  "packages/skeleton/src/correction-observation.mjs",
  "packages/skeleton/src/loadouts/contributor.ts",
  "packages/skeleton/src/loadouts/executor-supports.ts",
  "packages/skeleton/src/loadouts/feedback.ts",
  "packages/skeleton/src/loadouts/goal-alignment.ts",
  "packages/skeleton/src/loadouts/process-cost.ts",
  "packages/skeleton/src/loadouts/prompt-support.ts",
  "packages/skeleton/src/plan-refutation-protocol.ts",
  "packages/skeleton/src/usage-observation.mjs",
  "packages/skeleton/src/verification-host.ts",
  "packages/skeleton/src/verification-worktree.ts",
  "packages/skeleton/src/verification-protocol.ts",
  "packages/skeleton/src/verification.ts",
  "packages/skeleton/src/worker-protocol.ts",
  "packages/skeleton/src/worker-store.ts",
  "packages/skeleton/src/worker-transport.ts",
  "packages/skeleton/src/writer-teardown.mjs",
  "packages/skeleton/test/feedback-audit-source.test.ts",
  "packages/skeleton/test/feedback-fixtures.test.ts",
  "packages/skeleton/test/feedback-v2.test.ts",
  "scripts/feedback-commit-msg.mjs",
  "scripts/feedback-evidence.mjs",
];

const harnessSources = (root) => [
  ...commonSources,
  docRelative(root, "control", "budgets.json"),
  docRelative(root, "discovery", "harness-smoke-2026-09-07.json"),
  docRelative(root, "discovery", "harness-smoke-2026-09-07.md"),
  docRelative(root, "discovery", "harness-smoke-2026-09-07/claude-bare.json"),
  docRelative(root, "discovery", "harness-smoke-2026-09-07/claude.json"),
  docRelative(root, "discovery", "harness-smoke-2026-09-07/codex.json"),
  docRelative(root, "evidence", "WO-042/harness-context.json"),
  docRelative(root, "evidence", "WO-042/harness-live/executor-001.json"),
  docRelative(root, "evidence", "WO-042/harness-live/executor-002.json"),
  docRelative(root, "evidence", "WO-042/harness-live/executor-003.json"),
  docRelative(root, "evidence", "WO-042/harness-live/release-close-001.json"),
  docRelative(root, "evidence", "WO-042/harness-live/release-close-002.json"),
  docRelative(root, "evidence", "WO-042/harness-live/reviewer-001.json"),
  docRelative(root, "evidence", "WO-042/harness-live/reviewer-002.json"),
  docRelative(root, "evidence", "WO-042/harness-live/reviewer-003.json"),
  docRelative(root, "evidence", "WO-042/harness-live/verifier-001.json"),
  docRelative(root, "evidence", "WO-042/harness-live/verifier-002.json"),
  docRelative(
    root,
    "evidence",
    "WO-042/harness-live/writer-foreign-dead-001.json",
  ),
  docRelative(
    root,
    "evidence",
    "WO-042/harness-live/writer-foreign-dead-002.json",
  ),
  docRelative(
    root,
    "evidence",
    "WO-042/harness-live/writer-foreign-live-001.json",
  ),
  docRelative(
    root,
    "evidence",
    "WO-042/harness-live/writer-foreign-live-002.json",
  ),
  "packages/skeleton/src/feedback-boundary.ts",
  "packages/skeleton/src/feedback-source-comments.ts",
  "packages/skeleton/src/gate-deadlines.mjs",
  "packages/skeleton/src/gate-evidence.mjs",
  "packages/skeleton/src/harness-command.ts",
  "packages/skeleton/src/harness-host.ts",
  "packages/skeleton/src/subagent-budget.ts",
  "packages/skeleton/src/observed-facts.ts",
  "packages/skeleton/src/correction-observation.mjs",
  "packages/skeleton/src/loadouts/contributor.ts",
  "packages/skeleton/src/loadouts/executor-supports.ts",
  "packages/skeleton/src/loadouts/feedback.ts",
  "packages/skeleton/src/loadouts/goal-alignment.ts",
  "packages/skeleton/src/loadouts/process-cost.ts",
  "packages/skeleton/src/loadouts/prompt-support.ts",
  "packages/skeleton/src/usage-observation.mjs",
  "packages/skeleton/src/writer-teardown.mjs",
  "scripts/harness-context.mjs",
  "scripts/harness-evidence.mjs",
  "scripts/lib/harness-context.mjs",
  "scripts/lib/harness.mjs",
  "scripts/lib/paths.mjs",
  "scripts/lib/process-budget.mjs",
  "scripts/lib/terms.mjs",
  "scripts/terms.mjs",
];

/** The recorded source inventory for one launchpad: kit files keep their
 * repository-relative names and document inputs follow the configured roots. */
export const evidenceSources = (root) => ({
  authority: authoritySources(root),
  "artifact-identity": artifactIdentitySources(root),
  verification: verificationSources(root),
  feedback: feedbackSources(root),
  harness: harnessSources(root),
});
