import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
  rmSync,
  existsSync,
  renameSync,
  unlinkSync,
} from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { setTimeout as delay } from "node:timers/promises";
import { decodeLog } from "@dotln/kernel";
import { ResidentHost } from "@dotln/skeleton/dist/src/resident-host.js";
import {
  ResidentStore,
  recordPresence,
} from "@dotln/skeleton/dist/src/resident-store.js";
import { consoleChildEnvironment } from "@dotln/skeleton/dist/src/console-commands.js";
import {
  liveCommand,
  invokeLiveCommand,
  renderLiveView,
  watchLiveView,
} from "../src/live.js";

const root = fileURLToPath(new URL("../../../../", import.meta.url));
const cli = join(root, "packages/console/dist/src/cli.js");
const { missionConfiguration } = await import(
  pathToFileURL(join(root, "scripts/resident-bind.mjs")).href
);
const index =
  "# Work orders\n\nThis file is generated by `npm run work-orders -- index`.\n\n## Active\n\n### WO-117\n\n- State: active.\n- Dependencies: typed; dependency-ready.\n";
const until = async (check: () => boolean) => {
  for (let i = 0; i < 200; i++) {
    if (check()) return;
    await delay(20);
  }
  assert.fail("live observation timed out");
};
const host = async (t: test.TestContext) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-live-"));
  const indexPath = join(directory, "index.md");
  writeFileSync(indexPath, index);
  const resident = new ResidentHost({
    directory,
    policyId: "contributor.mission-check",
    workOrderIndexPath: indexPath,
    commandRoot: root,
    configuration: missionConfiguration({
      kind: "script",
      effect: "repo.read",
      surface: "fixture.source",
      resources: { files: 1, lines: 0, tokens: 0 },
      command: [process.execPath, "-e", "process.stdout.write('ok\\n')"],
      cwd: directory,
      timeoutMs: 1000,
      expectedStdoutSha256: "00".repeat(32),
    }),
    now: () => 0,
  });
  const abort = new AbortController();
  const running = resident.run({ tickMs: 3600000, signal: abort.signal });
  t.after(async () => {
    abort.abort();
    await running;
    rmSync(directory, { recursive: true, force: true });
  });
  let failure: unknown;
  void running.catch((error) => {
    failure = error;
  });
  await until(() => {
    if (failure) throw failure;
    return (
      existsSync(join(directory, "console/console-loopback-v1.json")) &&
      existsSync(join(directory, "runtime-status-v1.json"))
    );
  });
  return { directory, indexPath, resident };
};
const runCli = (args: string[], input?: string) =>
  new Promise<{ code: number | null; stdout: Buffer; stderr: Buffer }>(
    (done, reject) => {
      const child = spawn(process.execPath, [cli, ...args], {
        cwd: root,
        env: consoleChildEnvironment(process.env),
        stdio: ["pipe", "pipe", "pipe"],
      });
      const out: Buffer[] = [];
      const err: Buffer[] = [];
      child.stdout.on("data", (b: Buffer) => out.push(b));
      child.stderr.on("data", (b: Buffer) => err.push(b));
      child.once("error", reject);
      child.once("close", (code) =>
        done({ code, stdout: Buffer.concat(out), stderr: Buffer.concat(err) }),
      );
      child.stdin.end(input);
    },
  );

test("WO-117 combined passive view refreshes status, orders and audit without receipts and recovers", async (t) => {
  const { directory, indexPath, resident } = await host(t);
  const log = () => readFileSync(join(directory, "events.jsonl"), "utf8");
  const before = log();
  const frames: string[] = [];
  const watcher = watchLiveView(directory, (text) => frames.push(text));
  t.after(() => watcher.close());
  for (const text of [
    "Actors",
    "Live episodes",
    "Presence",
    "Open work orders (available)",
    "WO-117: active",
    "L0 RECEIPT",
    "CAUSAL TIMELINE",
    "GOVERNED RAW JSON",
  ])
    assert.ok(frames[0]!.includes(text), text);
  await delay(550);
  assert.equal(frames.length, 1);
  assert.equal(log(), before);
  await recordPresence(directory, "away", () => 10);
  await until(() => frames.at(-1)!.includes("away · signal away"));
  writeFileSync(indexPath, index.replace("State: active", "State: queued"));
  await resident.store.transaction(() => {});
  await until(() => frames.at(-1)!.includes("WO-117: queued"));
  const statusPath = join(directory, "runtime-status-v1.json");
  renameSync(statusPath, join(directory, "saved.json"));
  await until(() => frames.at(-1)!.includes("Runtime status unavailable"));
  writeFileSync(statusPath, "{");
  await delay(300);
  renameSync(join(directory, "saved.json"), statusPath);
  await until(() => !frames.at(-1)!.includes("Runtime status unavailable"));
  const validLog = log();
  writeFileSync(join(directory, "events.jsonl"), "{");
  await until(() => frames.at(-1)!.includes("Audit unavailable"));
  writeFileSync(join(directory, "events.jsonl"), validLog);
  await until(() => !frames.at(-1)!.includes("Audit unavailable"));
  assert.equal(
    decodeLog(log()).filter((e) => e.type.startsWith("ConsoleCommand")).length,
    0,
  );
  watcher.close();
  const count = frames.length;
  unlinkSync(statusPath);
  await delay(300);
  assert.equal(frames.length, count);
});

test(
  "WO-117 live command read, mutation, audit and refusal have invoke byte parity and exact receipts",
  { timeout: 30000 },
  async (t) => {
    const { directory } = await host(t);
    const events = () =>
      decodeLog(readFileSync(join(directory, "events.jsonl"), "utf8"));
    // A stable audit store isolates result bytes from the invocation receipts.
    const audit = join(directory, "audit");
    const auditStore = new ResidentStore(audit);
    await auditStore.transaction((tx) => tx.sample(0));
    for (const words of [
      ["skeleton.compiled-diff"],
      ["dotln.presence-away", "--store", directory],
      ["dotln.audit", "--store", audit],
      ["unknown.command"],
    ]) {
      const start = events().length;
      const alias = (
        {
          "skeleton.compiled-diff": "diff",
          "dotln.presence-away": "away",
        } as Record<string, string>
      )[words[0]!];
      const live = await invokeLiveCommand(
        directory,
        alias ?? JSON.stringify(words),
      );
      const added = events()
        .slice(start)
        .map((e) => e.type);
      assert.deepEqual(
        added,
        words[0] === "dotln.presence-away"
          ? [
              "ConsoleCommandInvoked",
              "OperatorPresenceObserved",
              "ClockSampled",
              "ConsoleCommandObserved",
            ]
          : ["ConsoleCommandInvoked", "ConsoleCommandObserved"],
      );
      const invoked = await runCli(["invoke", "--store", directory, ...words]);
      assert.equal(live.exitCode, invoked.code);
      assert.deepEqual(
        Buffer.from(live.stdoutBase64, "base64"),
        invoked.stdout,
      );
      assert.deepEqual(
        Buffer.from(live.stderrBase64, "base64"),
        invoked.stderr,
      );
      const interactive = await runCli(
        ["live", "--store", directory],
        JSON.stringify(words) + "\n:quit\n",
      );
      assert.equal(interactive.code, invoked.code);
      assert.deepEqual(interactive.stdout, invoked.stdout);
      if (invoked.stderr.length)
        assert.ok(interactive.stderr.includes(invoked.stderr));
      assert.ok(
        interactive.stderr.includes(
          Buffer.from(`[command exit ${invoked.code}]`),
        ),
      );
    }
  },
);

test(
  "WO-117 literal input, serial commands, EOF and invalid input",
  { timeout: 10000 },
  async (t) => {
    assert.deepEqual(
      liveCommand('["dotln.intent","spaces and \\n newline",""]'),
      { command: "dotln.intent", args: ["spaces and \n newline", ""] },
    );
    for (const bad of [
      "{}",
      "[]",
      "[1]",
      '["x",null]',
      '[""]',
      "constructor",
      "toString",
    ])
      assert.throws(() => liveCommand(bad));
    const { directory } = await host(t);
    const result = await runCli(
      ["live", "--store", directory],
      ':commands\n["dotln.presence-away","--store",' +
        JSON.stringify(directory) +
        ']\n["dotln.presence-back","--store",' +
        JSON.stringify(directory) +
        "]\n",
    );
    assert.equal(result.code, 0, result.stderr.toString());
    const receipts = decodeLog(
      readFileSync(join(directory, "events.jsonl"), "utf8"),
    ).filter((e) => e.type === "ConsoleCommandInvoked");
    assert.deepEqual(
      receipts.map((e) => (e.payload as { command: string }).command),
      ["dotln.presence-away", "dotln.presence-back"],
    );
    const invalid = await runCli(["live", "--store", directory], "{\n");
    assert.equal(invalid.code, 1);
    assert.ok(invalid.stderr.toString().includes("invalid input"));
    assert.ok(renderLiveView(directory).includes("present · signal back"));
  },
);

test(
  "WO-117 signals abort active invocation and contract fetches",
  { timeout: 10000 },
  async (t) => {
    for (const line of ['["skeleton.compiled-diff"]', ":commands"]) {
      const directory = mkdtempSync(join(tmpdir(), "dotln-live-abort-"));
      let accepted = false;
      const server = createServer((_req, res) => {
        accepted = true;
        res.writeHead(200, { "content-type": "application/json" });
        res.write(" ");
      });
      await new Promise<void>((done) => server.listen(0, "127.0.0.1", done));
      const address = server.address();
      assert.ok(address && typeof address !== "string");
      mkdirSync(join(directory, "console"), { mode: 0o700 });
      writeFileSync(
        join(directory, "console/console-loopback-v1.json"),
        JSON.stringify({
          version: 1,
          host: "127.0.0.1",
          port: address.port,
          token: "a".repeat(64),
        }),
        { mode: 0o600 },
      );
      const child = spawn(
        process.execPath,
        [cli, "live", "--store", directory],
        { stdio: ["pipe", "pipe", "pipe"] },
      );
      let err = "";
      child.stdout.resume();
      child.stderr.on("data", (chunk) => {
        err += chunk;
      });
      const exit = new Promise<number | null>((done) =>
        child.once("close", done),
      );
      t.after(() => {
        child.kill("SIGKILL");
        server.closeAllConnections();
        server.close();
        rmSync(directory, { recursive: true, force: true });
      });
      child.stdin.write(line + "\n");
      await until(() => accepted);
      child.kill("SIGTERM");
      assert.equal(await exit, 0, err);
      assert.ok(!err.includes("invalid input"));
    }
  },
);

test("WO-117 idle clock samples do not repaint and compact audit fields cannot forge lines", async (t) => {
  const { directory, resident } = await host(t);
  const frames: string[] = [];
  const watcher = watchLiveView(directory, (text) => frames.push(text));
  t.after(() => watcher.close());
  await resident.store.transaction((tx) => tx.sample(100));
  await delay(1100);
  assert.equal(
    frames.length,
    1,
    "recorded-clock ticks alone must not flood the view",
  );
  const original = readFileSync(join(directory, "events.jsonl"), "utf8");
  writeFileSync(
    join(directory, "events.jsonl"),
    JSON.stringify({
      schemaVersion: 1,
      eventId: "evt_1",
      type: "EpisodeTerminated",
      occurredAt: 101,
      actorId: "actor\nFORGED\t\u001b\u202e",
      workstreamId: "test",
      episodeId: "episode",
      payload: {},
    }) + "\n",
  );
  const text = renderLiveView(directory);
  assert.ok(text.includes("actor?FORGED???"));
  assert.ok(!text.includes("\nFORGED"));
  assert.ok(!/[\u001b\u202e]/u.test(text));
  writeFileSync(join(directory, "events.jsonl"), original);
});

test("WO-117 generic payloads and inherited names cannot stop refresh", async (t) => {
  const directory = mkdtempSync(join(tmpdir(), "dotln-live-null-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const frames: string[] = [];
  const watcher = watchLiveView(directory, (text) => frames.push(text));
  t.after(() => watcher.close());
  const records: string[] = [];
  for (const [i, [type, payload, label]] of [
    ["GenericEvent", null, "GenericEvent"],
    ["constructor", null, "constructor"],
    ["toString", null, "toString"],
    [
      "ConsoleCommandObserved",
      { exitCode: { toString: "not callable" } },
      "Console command finished (exit unknown)",
    ],
  ].entries()) {
    records.push(
      JSON.stringify({
        schemaVersion: 1,
        eventId: `evt_${i + 1}`,
        type,
        occurredAt: i,
        actorId: "actor",
        workstreamId: "test",
        payload,
      }),
    );
    writeFileSync(join(directory, "events.jsonl"), records.join("\n") + "\n");
    await until(() => frames.at(-1)!.includes("  " + label));
    assert.ok(!frames.at(-1)!.includes("Audit unavailable"));
  }
  assert.throws(() => liveCommand("constructor", directory));
  assert.throws(() => liveCommand("toString", directory));
});
