import { array, object, optionalString, string, strings } from "./values.js";

export interface TextRow {
  readonly key: string;
  readonly line: number;
  readonly values: Readonly<Record<string, string>>;
}

/** These are pinned repository formats, not a general Markdown implementation. */
export function tableRows(
  text: string,
  header: readonly string[],
): readonly TextRow[] {
  const result: TextRow[] = [];
  let matched = false;
  let reading = false;
  for (const [index, line] of text.split("\n").entries()) {
    if (!line.startsWith("|")) {
      reading = false;
      continue;
    }
    const cells = line
      .trim()
      .slice(1, -1)
      .split(/(?<!\\)\|/u)
      .map((cell) => cell.trim().replaceAll("\\|", "|"));
    if (cells.every((cell) => /^:?-+:?$/u.test(cell))) continue;
    if (
      cells.length === header.length &&
      cells.every((cell, i) => cell === header[i])
    ) {
      matched = true;
      reading = true;
      continue;
    }
    if (!reading) continue;
    if (cells.length !== header.length)
      throw new Error("table column count changed");
    result.push({
      key: cells[0]!,
      line: index + 1,
      values: Object.fromEntries(header.map((key, i) => [key, cells[i]!])),
    });
  }
  if (!matched) throw new Error("expected table header is absent");
  return result;
}

export const plainText = (value: string): string =>
  value
    .replace(/<br\s*\/?\s*>/giu, "; ")
    .replace(/\[([^\]]+)\]\([^\s)]+\)/gu, "$1")
    .replace(/`([^`]+)`/gu, "$1")
    .replace(/\*\*([^*]+)\*\*/gu, "$1")
    .replace(/\\([|_])/gu, "$1")
    .trim();

export const markdownLinks = (value: string): readonly string[] =>
  [...value.matchAll(/\[[^\]]+\]\(([^\s)]+)\)/gu)].map((match) => match[1]!);

export const CAPABILITY_HEADER = [
  "Capability and declared scope",
  "Current level",
  "Target level",
  "Required dimensions",
  "Evidence links",
  "Dependencies",
  "Last change",
  "Next smallest promotable increment",
  "Blocking gate",
  "Efficiency",
] as const;
export const PUBLICATION_HEADER = ["Section", "Audiences", "Status"] as const;

export function parseCapabilities(text: string): readonly TextRow[] {
  if (!text.startsWith("# Capability table v1\n"))
    throw new Error("capability format changed");
  const headers = [
    CAPABILITY_HEADER,
    [
      "Capability key",
      "New staged evidence",
      "Blocking-gate reassessment",
      "Disposition",
    ],
    [
      "Capability and scope",
      "Current level",
      "Target",
      "Evidence",
      "Next increment and dependencies",
      "Blocking gate",
    ],
    [
      "Capability and scope",
      "Current assessment",
      "Evidence and remaining gate",
    ],
    [
      "Capability and scope",
      "Current level",
      "Target",
      "Evidence and remaining gate",
    ],
  ];
  const lines = text.split("\n");
  const used: (readonly string[])[] = [];
  for (let index = 0; index < lines.length - 1; index++) {
    if (
      !lines[index]!.startsWith("|") ||
      !/^\|[ :|\-]+\|$/u.test(lines[index + 1]!)
    )
      continue;
    const cells = lines[index]!.trim()
      .slice(1, -1)
      .split(/(?<!\\)\|/u)
      .map((cell) => cell.trim());
    const header = headers.find(
      (candidate) => candidate.join("\0") === cells.join("\0"),
    );
    if (!header) throw new Error("unrecognized capability table header");
    if (!used.includes(header)) used.push(header);
  }
  if (!used.includes(CAPABILITY_HEADER))
    throw new Error("capability inventory is absent");
  return used
    .flatMap((header) => tableRows(text, header))
    .sort((left, right) => left.line - right.line)
    .map((row) => ({
      ...row,
      values: {
        Assessment:
          lines
            .slice(0, row.line)
            .filter((line) => line.startsWith("## "))
            .at(-1)
            ?.slice(3) ?? "unknown",
        ...row.values,
      },
    }));
}

export function parseWorkOrderIndex(text: string): readonly TextRow[] {
  if (
    !text.startsWith("# Work orders\n") ||
    !text.includes("This file is generated by")
  )
    throw new Error("expected generated work-order index");
  const rows: TextRow[] = [];
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const heading = lines[i]!.match(/^### (WO-\d{3})$/u);
    if (!heading) continue;
    const values: Record<string, string> = {};
    const start = i;
    while (i + 1 < lines.length && !/^#{1,3} /u.test(lines[i + 1]!)) {
      const line = lines[++i]!;
      const field = line.match(/^- ([^:]+(?:\([^)]*\))?): (.+)$/u);
      if (field) values[field[1]!] = field[2]!;
      if (line.startsWith("[WO-")) values["title"] = plainText(line);
    }
    if (!values["State"] || !values["Authority"])
      throw new Error("incomplete work-order index row");
    rows.push({ key: heading[1]!, line: start + 1, values });
  }
  if (!rows.length) throw new Error("work-order index contains no rows");
  return rows;
}

export function parseReleases(text: string): readonly TextRow[] {
  const lines = text.trimEnd().split("\n");
  if (lines.shift() !== "TAG\tCOMMIT\tAPPLICATION\tWORK ORDERS")
    throw new Error("release-list header changed");
  return lines.map((line, index) => {
    const cells = line.split("\t");
    if (
      cells.length !== 4 ||
      !/^v\d+\.\d+\.\d+$/u.test(cells[0]!) ||
      !/^[a-f0-9]{40,64}$/u.test(cells[1]!)
    )
      throw new Error("invalid release-list row");
    return {
      key: cells[0]!,
      line: index + 2,
      values: {
        tag: cells[0]!,
        commit: cells[1]!,
        application: cells[2]!,
        workOrders: cells[3]!,
      },
    };
  });
}

export function parseConstellation(text: string): readonly TextRow[] {
  const lines = text.trimEnd().split("\n");
  if (!lines.at(-1)?.startsWith("Group Beacon | "))
    throw new Error("constellation group line is absent");
  return lines.map((line, index): TextRow => {
    const parts = line.split(" | ");
    const heading = parts[0]!;
    if (heading === "Group Beacon") {
      if (
        parts.length !== 4 ||
        parts[2] !== "group-v1" ||
        !/^active=\d+ /u.test(parts[1]!)
      )
        throw new Error("invalid constellation group");
      return {
        key: "group",
        line: index + 1,
        values: { counts: parts[1]!, codebook: parts[2]!, storage: parts[3]! },
      };
    }
    if (!heading.startsWith("Beacon ") || ![3, 7, 9].includes(parts.length))
      throw new Error("invalid constellation row");
    const key = heading.slice(7);
    if (!key) throw new Error("missing constellation address");
    if (parts.length === 3)
      return {
        key,
        line: index + 1,
        values: { observation: parts[1]!, age: parts[2]! },
      };
    if (parts.length === 7)
      return {
        key,
        line: index + 1,
        values: {
          observation: parts[1]!,
          provenance: parts[2]!,
          age: parts[3]!,
          codebook: parts[4]!,
          storage: parts[5]!,
          provenanceCheck: parts[6]!,
        },
      };
    return {
      key,
      line: index + 1,
      values: {
        phase: parts[1]!,
        verdict: parts[2]!,
        effort: parts[3]!,
        provenance: parts[4]!,
        age: parts[5]!,
        codebook: parts[6]!,
        storage: parts[7]!,
        provenanceCheck: parts[8]!,
      },
    };
  });
}

export function parsePendingRungs(text: string): readonly TextRow[] {
  if (!text.startsWith("# Roadmap — application release ladder\n"))
    throw new Error("roadmap heading changed");
  return text.split("\n").flatMap((line, index) =>
    line.startsWith("## Application version pending — ")
      ? [
          {
            key: line.slice(3),
            line: index + 1,
            values: {
              rung: line.slice(3),
              status: "pending (roadmap heading)",
            },
          },
        ]
      : [],
  );
}

export interface RefutationSummary {
  readonly receipt: string;
  readonly format: string;
  readonly scope: string;
  readonly planVerdict: string;
  readonly holdReasons: readonly string[];
  readonly rows: readonly {
    readonly workOrder: string;
    readonly verdict: string;
    readonly reason: string;
    readonly thesis: string | null;
    readonly capabilityRow: string | null;
    readonly roles: readonly string[];
  }[];
}

/** Latest is selected by the dated immutable filename, never by a prose verdict. */
export function parseRefutation(
  ref: string,
  value: unknown,
): RefutationSummary {
  const record = object(value);
  const versioned = record["schemaVersion"] === "plan-refutation-receipt-v1";
  if (
    !versioned &&
    !/^docs\/planning\/refutations\/2026-09-06-phase-two-redirect(?:-00[2-6])?\.json$/u.test(
      ref,
    )
  )
    throw new Error("unsupported refutation receipt format");
  const result = versioned ? object(record["result"]) : record;
  const verdict = string(result["planVerdict"]);
  if (!["pass", "hold"].includes(verdict))
    throw new Error("invalid plan verdict");
  return {
    receipt: versioned
      ? string(record["receiptId"])
      : ref.split("/").at(-1)!.slice(0, -5),
    format: versioned
      ? "plan-refutation-receipt-v1"
      : "manual-redirect-2026-09-06",
    scope: versioned
      ? string(object(record["pass"])["kind"])
      : "planning redirect",
    planVerdict: verdict,
    holdReasons: array(result["holdReasons"]).map((hold) =>
      typeof hold === "string"
        ? hold
        : `${string(object(hold)["workOrderId"])} / ${string(object(hold)["criterionId"])}: ${string(object(hold)["reason"])}`,
    ),
    rows: array(result["orders"]).map((item) => {
      const row = object(item);
      return {
        workOrder: string(row["workOrderId"]),
        verdict: string(row["verdict"]),
        reason: string(row["reason"]),
        thesis: optionalString(row["thesis"]) ?? null,
        capabilityRow: optionalString(row["capabilityRow"]) ?? null,
        roles: strings(row["rolesServed"]),
      };
    }),
  };
}
